**Pipeline Example: 01 (Using 2 Features Engineering Techniques)**

**Importing Pipelines**

In [163]:
from sklearn.pipeline import Pipeline

**Feature Scaling**

In [164]:
#Transformation Technique
from sklearn.preprocessing import StandardScaler

**Importing Regression**

In [165]:
#Estimator
from sklearn.linear_model import LogisticRegression

**Tuples**

In [166]:
steps = [("standard_scaler",StandardScaler()),("classifier",LogisticRegression())]

In [167]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

**Converting Steps into Pipeline**

In [168]:
pipe = Pipeline(steps)

In [169]:
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

**Visualization of the Pipeline**

In [170]:
from sklearn import set_config
set_config(display ="diagram")

**Create a Dataset**

In [171]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples= 2000)

In [172]:
X.shape

(2000, 20)

In [173]:
y.shape

(2000,)

**Train Test Split**

In [174]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)


In [175]:
X_train

array([[ 2.14220664, -0.31668157, -0.85894568, ..., -0.7628545 ,
        -0.53002579,  1.3847069 ],
       [ 0.54671917, -1.66921748,  0.33616732, ...,  0.42737563,
         1.29894351,  1.16913492],
       [-0.95304704,  1.09302839,  1.58878601, ...,  1.13064514,
        -0.89142743,  0.10754384],
       ...,
       [-0.21896304,  0.20384254, -2.49515303, ..., -0.30360674,
        -0.05878891,  1.32752385],
       [-2.15132467,  1.33881851,  1.47262891, ..., -1.27260761,
        -0.69669988, -0.4269171 ],
       [-0.66234345, -2.22841444,  1.21422666, ...,  1.67017302,
         1.76792252,  0.66731813]])

**Fitting Data into the Pipeline**

In [176]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [177]:
pipe.predict(X_test)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,

**Pipeline Example: 02 (Using 3 Features Engineering Techniques)**

**Feature Scaling, Principal Component Analysis, and Applying Support Vector Machine.**

In [178]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [179]:
steps2 = [("feature_scaling",StandardScaler()),("Principal Component Analysis",PCA(n_components= 4)),("classifier",SVC())]

In [180]:
pipe2 = Pipeline(steps2)

In [181]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('feature_scaling', StandardScaler()),
                ('Principal Component Analysis', PCA(n_components=4)),
                ('classifier', SVC())])

In [182]:
#Independentlly Using the Key Name
#pipe2['feature_scaling'].fit_transform(X_train)

In [183]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('feature_scaling', StandardScaler()),
                ('Principal Component Analysis', PCA(n_components=4)),
                ('classifier', SVC())])

In [184]:
pipe2.predict(X_test)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,

**Pipeline Example: 03 (Using Column Transformers)**

**Handling Missing values**

In [185]:
from sklearn.impute import SimpleImputer
import numpy as np

**Numerical Processing Pipeline**

In [186]:
#Numerical Processing Pipeline
numeric_processor = Pipeline(
    steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy="mean")),
          ("scaler",StandardScaler())]

)

In [187]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

**Categorical Processing Pipeline**

In [188]:
#Categorical Processing Pipeline

#categorical_processor = Pipeline(
#    steps=[("imputation_constant",SimpleImputer(fill_value="missing",strategy="constant")),
#          ("scaler",StandardScaler())]

#)

from sklearn.preprocessing import OneHotEncoder
categorical_processor = Pipeline(
    steps=[("imputation_constant",SimpleImputer(fill_value="missing",strategy="constant")),
          ("onehotencoder",OneHotEncoder(handle_unknown="ignore"))]

)



In [189]:
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))])

**Combine Processing Technique**

In [190]:
from sklearn.compose import ColumnTransformer

preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,["gender","City"]),
    ("numerical",numeric_processor,["age","height"])]


)

In [191]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

**Pipeline**

In [192]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())
pipe


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])